/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OTokenRouteImport } from './routes/o.$token'
import { Route as AuthenticatedTimeclockReportRouteImport } from './routes/_authenticated/timeclock-report'
import { Route as AuthenticatedTimeclockRouteImport } from './routes/_authenticated/timeclock'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSalesSummaryRouteImport } from './routes/_authenticated/sales-summary'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPrintSettingsRouteImport } from './routes/_authenticated/print-settings'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedPayslipRouteImport } from './routes/_authenticated/payslip'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedEosAdminRouteImport } from './routes/_authenticated/eos-admin'
import { Route as AuthenticatedEndOfShiftRouteImport } from './routes/_authenticated/end-of-shift'
import { Route as AuthenticatedDiscountsRouteImport } from './routes/_authenticated/discounts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedBundlesRouteImport } from './routes/_authenticated/bundles'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OTokenRoute = OTokenRouteImport.update({
  id: '/o/$token',
  path: '/o/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimeclockReportRoute =
  AuthenticatedTimeclockReportRouteImport.update({
    id: '/timeclock-report',
    path: '/timeclock-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTimeclockRoute = AuthenticatedTimeclockRouteImport.update({
  id: '/timeclock',
  path: '/timeclock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesSummaryRoute =
  AuthenticatedSalesSummaryRouteImport.update({
    id: '/sales-summary',
    path: '/sales-summary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrintSettingsRoute =
  AuthenticatedPrintSettingsRouteImport.update({
    id: '/print-settings',
    path: '/print-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayslipRoute = AuthenticatedPayslipRouteImport.update({
  id: '/payslip',
  path: '/payslip',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEosAdminRoute = AuthenticatedEosAdminRouteImport.update({
  id: '/eos-admin',
  path: '/eos-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEndOfShiftRoute = AuthenticatedEndOfShiftRouteImport.update({
  id: '/end-of-shift',
  path: '/end-of-shift',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscountsRoute = AuthenticatedDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBundlesRoute = AuthenticatedBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/bundles': typeof AuthenticatedBundlesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discounts': typeof AuthenticatedDiscountsRoute
  '/end-of-shift': typeof AuthenticatedEndOfShiftRoute
  '/eos-admin': typeof AuthenticatedEosAdminRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payslip': typeof AuthenticatedPayslipRoute
  '/pos': typeof AuthenticatedPosRoute
  '/print-settings': typeof AuthenticatedPrintSettingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-summary': typeof AuthenticatedSalesSummaryRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/timeclock': typeof AuthenticatedTimeclockRoute
  '/timeclock-report': typeof AuthenticatedTimeclockReportRoute
  '/o/$token': typeof OTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/bundles': typeof AuthenticatedBundlesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discounts': typeof AuthenticatedDiscountsRoute
  '/end-of-shift': typeof AuthenticatedEndOfShiftRoute
  '/eos-admin': typeof AuthenticatedEosAdminRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/payslip': typeof AuthenticatedPayslipRoute
  '/pos': typeof AuthenticatedPosRoute
  '/print-settings': typeof AuthenticatedPrintSettingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales-summary': typeof AuthenticatedSalesSummaryRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/timeclock': typeof AuthenticatedTimeclockRoute
  '/timeclock-report': typeof AuthenticatedTimeclockReportRoute
  '/o/$token': typeof OTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/bundles': typeof AuthenticatedBundlesRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discounts': typeof AuthenticatedDiscountsRoute
  '/_authenticated/end-of-shift': typeof AuthenticatedEndOfShiftRoute
  '/_authenticated/eos-admin': typeof AuthenticatedEosAdminRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/payslip': typeof AuthenticatedPayslipRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/print-settings': typeof AuthenticatedPrintSettingsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales-summary': typeof AuthenticatedSalesSummaryRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/timeclock': typeof AuthenticatedTimeclockRoute
  '/_authenticated/timeclock-report': typeof AuthenticatedTimeclockReportRoute
  '/o/$token': typeof OTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/audit-log'
    | '/bundles'
    | '/customers'
    | '/dashboard'
    | '/discounts'
    | '/end-of-shift'
    | '/eos-admin'
    | '/history'
    | '/inventory'
    | '/menu'
    | '/payments'
    | '/payslip'
    | '/pos'
    | '/print-settings'
    | '/reports'
    | '/sales-summary'
    | '/staff'
    | '/timeclock'
    | '/timeclock-report'
    | '/o/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/audit-log'
    | '/bundles'
    | '/customers'
    | '/dashboard'
    | '/discounts'
    | '/end-of-shift'
    | '/eos-admin'
    | '/history'
    | '/inventory'
    | '/menu'
    | '/payments'
    | '/payslip'
    | '/pos'
    | '/print-settings'
    | '/reports'
    | '/sales-summary'
    | '/staff'
    | '/timeclock'
    | '/timeclock-report'
    | '/o/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/audit-log'
    | '/_authenticated/bundles'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/discounts'
    | '/_authenticated/end-of-shift'
    | '/_authenticated/eos-admin'
    | '/_authenticated/history'
    | '/_authenticated/inventory'
    | '/_authenticated/menu'
    | '/_authenticated/payments'
    | '/_authenticated/payslip'
    | '/_authenticated/pos'
    | '/_authenticated/print-settings'
    | '/_authenticated/reports'
    | '/_authenticated/sales-summary'
    | '/_authenticated/staff'
    | '/_authenticated/timeclock'
    | '/_authenticated/timeclock-report'
    | '/o/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OTokenRoute: typeof OTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$token': {
      id: '/o/$token'
      path: '/o/$token'
      fullPath: '/o/$token'
      preLoaderRoute: typeof OTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeclock-report': {
      id: '/_authenticated/timeclock-report'
      path: '/timeclock-report'
      fullPath: '/timeclock-report'
      preLoaderRoute: typeof AuthenticatedTimeclockReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timeclock': {
      id: '/_authenticated/timeclock'
      path: '/timeclock'
      fullPath: '/timeclock'
      preLoaderRoute: typeof AuthenticatedTimeclockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales-summary': {
      id: '/_authenticated/sales-summary'
      path: '/sales-summary'
      fullPath: '/sales-summary'
      preLoaderRoute: typeof AuthenticatedSalesSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/print-settings': {
      id: '/_authenticated/print-settings'
      path: '/print-settings'
      fullPath: '/print-settings'
      preLoaderRoute: typeof AuthenticatedPrintSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payslip': {
      id: '/_authenticated/payslip'
      path: '/payslip'
      fullPath: '/payslip'
      preLoaderRoute: typeof AuthenticatedPayslipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eos-admin': {
      id: '/_authenticated/eos-admin'
      path: '/eos-admin'
      fullPath: '/eos-admin'
      preLoaderRoute: typeof AuthenticatedEosAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/end-of-shift': {
      id: '/_authenticated/end-of-shift'
      path: '/end-of-shift'
      fullPath: '/end-of-shift'
      preLoaderRoute: typeof AuthenticatedEndOfShiftRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discounts': {
      id: '/_authenticated/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AuthenticatedDiscountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bundles': {
      id: '/_authenticated/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof AuthenticatedBundlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBundlesRoute: typeof AuthenticatedBundlesRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscountsRoute: typeof AuthenticatedDiscountsRoute
  AuthenticatedEndOfShiftRoute: typeof AuthenticatedEndOfShiftRoute
  AuthenticatedEosAdminRoute: typeof AuthenticatedEosAdminRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPayslipRoute: typeof AuthenticatedPayslipRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedPrintSettingsRoute: typeof AuthenticatedPrintSettingsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesSummaryRoute: typeof AuthenticatedSalesSummaryRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedTimeclockRoute: typeof AuthenticatedTimeclockRoute
  AuthenticatedTimeclockReportRoute: typeof AuthenticatedTimeclockReportRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBundlesRoute: AuthenticatedBundlesRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscountsRoute: AuthenticatedDiscountsRoute,
  AuthenticatedEndOfShiftRoute: AuthenticatedEndOfShiftRoute,
  AuthenticatedEosAdminRoute: AuthenticatedEosAdminRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPayslipRoute: AuthenticatedPayslipRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedPrintSettingsRoute: AuthenticatedPrintSettingsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesSummaryRoute: AuthenticatedSalesSummaryRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedTimeclockRoute: AuthenticatedTimeclockRoute,
  AuthenticatedTimeclockReportRoute: AuthenticatedTimeclockReportRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OTokenRoute: OTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
